name: Go

on:
  workflow_dispatch: # on button click
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: tdengine/tdengine:3.3.1.0
      options: --user root
      volumes:
        - /etc/apt/sources.list:/etc/apt/sources.list
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: start taosd
        run: nohup taosd &

      # - name: Install build-essential
      #   run: apt-get update && apt-get install -y build-essential curl

      # - name: Build
      #   run: go build ./...

      - name: Test
        run: go test ./...